# Generated by Django 2.1.7 on 2019-03-29 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsectFamilies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InsectGenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InsectSpecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.InsectGenes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InsectSubFamilies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.InsectFamilies')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InsectSuperFamilies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InsectTribes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subFamily', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.InsectSubFamilies')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='insectgenes',
            name='tribe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.InsectTribes'),
        ),
        migrations.AddField(
            model_name='insectfamilies',
            name='superFamily',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.InsectSuperFamilies'),
        ),
    ]
