# Generated by Django 2.1.7 on 2019-03-21 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190320_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('codeSite', models.CharField(max_length=200)),
                ('latitudeLambert72', models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True)),
                ('longitudeLambert72', models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True)),
                ('latitudeDec', models.DecimalField(decimal_places=10, max_digits=13)),
                ('longitudeDec', models.DecimalField(decimal_places=10, max_digits=13)),
                ('project', models.ManyToManyField(to='core.Project')),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Town')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PlaceType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
