# Generated by Django 2.1.7 on 2019-03-22 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='project',
            new_name='projects',
        ),
    ]
